version: '3'

# needed:
# docker-compose run django ./manage.py collectstatic --no-input
# docker-compose run django ./manage.py migrate
# docker-compose run django ./manage.py createsuperuser

services:

  nginx:
    image: nginx
    volumes:
      - ./nginx-config:/etc/nginx/conf.d:ro
      - ./static:/static:ro
    links:
      - django

  django:
    image: garncarz/dns-server
    build: .
    command: gunicorn --bind :8000 --forwarded-allow-ips="*" main.wsgi:application
    volumes:
      - ./data:/data
      - ./static:/static

  dns:
    image: garncarz/dns-server
    build: .
    command: ./manage.py dns_server
    ports:
      - 53:53
      - 53:53/udp
    volumes:
      - ./data:/data
