# Generated by Django 5.2.5 on 2025-08-31 11:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0003_redirection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pastebin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('content', models.TextField()),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('content_type', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
